export const CHANGE_NAME_VAL = 'CHANGE_NAME_VAL';
export const CHANGE_TYPE_VAL = 'CHANGE_TYPE_VAL';
export const CHANGE_TEXT_VAL = 'CHANGE_TEXT_VAL';
export const CHECK_BLACK_MANA = 'CHECK_BLACK_MANA';
export const CHECK_WHITE_MANA = 'CHECK_WHITE_MANA'; 

