export const CHANGE_NAME_VAL = 'CHANGE_NAME_VAL';
export const CHANGE_TYPE_VAL = 'CHANGE_TYPE_VAL';
export const CHANGE_TEXT_VAL = 'CHANGE_TEXT_VAL';
export const CHECK_BLACK_MANA = 'CHECK_BLACK_MANA';
export const CHECK_WHITE_MANA = 'CHECK_WHITE_MANA';
export const CHECK_RED_MANA = 'CHECK_RED_MANA'; 
export const CHECK_GREEN_MANA = 'CHECK_GREEN_MANA'; 
export const CHECK_BLUE_MANA = 'CHECK_BLUE_MANA'; 
export const CHECK_EXACT_COLORS = 'CHECK_EXACT_COLORS';
export const CHECK_EXCLUDE_COLORS = 'CHECK_EXCLUDE_COLORS';
export const SELECT_CARD_FORMAT = 'SELECT_CARD_FORMAT';
export const PUSH_CARD_FORMAT = 'PUSH_CARD_FORMAT';
export const INIT_AVAIL_FORMATS = 'INIT_AVAIL_FORMATS';
export const REMOVE_AVAIL_FORMAT = 'REMOVE_AVAIL_FORMATS';
export const REMOVE_CARD_FORMAT = 'REMOVE_CARD_FORMAT';
export const PUSH_AVAIL_FORMAT = 'PUSH_AVAIL_FORMAT'; 
export const INIT_AVAIL_SETS = 'INIT_AVAIL_SETS';
export const SELECT_CARD_SET = 'SELECT_CARD_SET';
export const PUSH_CARD_SET = 'PUSH_CARD_SET';
export const REMOVE_AVAIL_SET = 'REMOVE_AVAIL_SET';
export const REMOVE_CARD_SET = 'REMOVE_CARD_SET';
export const PUSH_AVAIL_SET = 'PUSH_AVAIL_SET';
export const INIT_AVAIL_SORT = 'INIT_AVAIL_SORT';
export const SELECT_SORT_FILTER = 'SELECT_SORT_FILTER';
export const SELECT_SORT_DIRECTION = 'SELECT_SORT_DIRECTION';
export const PUSH_SORT_FILTER = 'PUSH_SORT_FILTER';
export const REMOVE_AVAIL_SORT = 'REMOVE_AVAIL_SORT';
export const REMOVE_SORT_FILTER = 'REMOVE_SORT_FILTER';
export const PUSH_AVAIL_SORT = 'PUSH_AVAIL_SORT';



