export const CHANGE_NAME_VAL = 'CHANGE_NAME_VAL';
export const CHANGE_TYPE_VAL = 'CHANGE_TYPE_VAL';
export const CHANGE_TEXT_VAL = 'CHANGE_TEXT_VAL';
export const CHECK_BLACK_MANA = 'CHECK_BLACK_MANA';
export const CHECK_WHITE_MANA = 'CHECK_WHITE_MANA';
export const CHECK_RED_MANA = 'CHECK_RED_MANA'; 
export const CHECK_GREEN_MANA = 'CHECK_GREEN_MANA'; 
export const CHECK_BLUE_MANA = 'CHECK_BLUE_MANA'; 
export const CHECK_EXACT_COLORS = 'CHECK_EXACT_COLORS';
export const CHECK_EXCLUDE_COLORS = 'CHECK_EXCLUDE_COLORS';
export const SELECT_CARD_FORMAT = 'SELECT_CARD_FORMAT';
export const PUSH_CARD_FORMAT = 'PUSH_CARD_FORMAT';
export const INIT_AVAIL_FORMATS = 'INIT_AVAIL_FORMATS';
export const REMOVE_AVAIL_FORMAT = 'REMOVE_AVAIL_FORMATS';
 


